#
# Module manifest for module 'DefenderEndpointDeployment'
#
# Generated by: Lessi Coulibaly
#
# Generated on: 7/24/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'DefenderEndpointDeployment.psm1'

# Version number of this module.
ModuleVersion = '1.1.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '2634abd0-737a-45e7-8bee-9e97c1558817'

# Author of this module
Author = 'Lessi Coulibaly'

# Company or vendor of this module
CompanyName = 'Less-IT (AI and CyberSecurity)'

# Copyright statement for this module
Copyright = '(c) 2025 Lessi Coulibaly. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Comprehensive PowerShell module for Azure Arc onboarding and Microsoft Defender for Endpoint (MDE) integration through Defender for Servers. Features enterprise-grade prerequisites validation covering OS compatibility, system requirements, PowerShell environment, network connectivity, Windows services, security configuration, and MDE readiness. Includes automated remediation script generation, detailed reporting, multi-device batch processing for enterprise environments, comprehensive Azure Arc diagnostic tools for troubleshooting and support, and post-deployment Defender for Servers pricing configuration at the resource level.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Az.Accounts'; ModuleVersion = '2.12.1'; }, 
               @{ModuleName = 'Az.Resources'; ModuleVersion = '6.0.0'; })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'New-AzureArcDevice', 'Test-AzureArcPrerequisite', 
               'Deploy-DefenderForServers', 'Get-AzureArcDiagnostic', 
               'Set-AzureArcResourcePricing'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Azure', 'AzureArc', 'Defender', 'MicrosoftDefender', 'Endpoint', 'Security', 'Management', 'Deployment', 'Prerequisites', 'MDE', 'Enterprise', 'PowerShell', 'Automation', 'Diagnostics', 'Troubleshooting', 'Logging', 'Pricing', 'Configuration', 'PostDeployment')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/LessIT/DefenderEndpointDeployment/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://lessit.net/projects/DefenderEndpointDeployment'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## Version 1.1.0 - Enhanced Functionality

### 🚀 New Features & Improvements
- **Enhanced Module Stability**: Improved error handling and performance optimizations
- **Documentation Updates**: Comprehensive README refresh with better organization
- **Code Quality**: Refined function implementations and better parameter validation
- **User Experience**: Enhanced interactive menu system with improved navigation
- **Compatibility**: Extended compatibility testing and validation

### 🔧 Technical Enhancements
- Optimized module loading and function exports
- Improved Azure authentication handling
- Enhanced file management and organization
- Better error reporting and troubleshooting guidance
- Streamlined deployment workflows

### 📋 Maintenance
- Updated dependencies and requirements validation
- Refined module structure and organization
- Enhanced documentation and help content
- Improved PowerShell Gallery compatibility

---

## Version 1.0.0 - Initial Release

### 🎯 Enterprise-Grade Azure Arc Deployment Module
Complete PowerShell solution for Azure Arc onboarding, Microsoft Defender integration, and enterprise deployment management.

For complete documentation and support: https://lessit.net
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://lessit.net/help/DefenderEndpointDeployment'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

