#
# Module manifest for module 'ServerProtection'
#
# Generated by: Lessi Coulibaly
#
# Generated on: 7/24/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ServerProtection.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '2634abd0-737a-45e7-8bee-9e97c1558817'

# Author of this module
Author = 'Lessi Coulibaly'

# Company or vendor of this module
CompanyName = 'Less-IT (AI and CyberSecurity)'

# Copyright statement for this module
Copyright = '(c) 2025 Lessi Coulibaly. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Comprehensive PowerShell module for server protection through Azure Arc onboarding and Microsoft Defender for Servers (DFS) integration. Microsoft Defender for Servers provides advanced threat protection, vulnerability assessment, and security monitoring for server workloads in Microsoft Defender for Cloud. Features enterprise-grade prerequisites validation covering OS compatibility, system requirements, PowerShell environment, network connectivity, Windows services, security configuration, and Azure Arc readiness. Includes automated remediation script generation, detailed reporting, multi-device batch processing for enterprise environments, comprehensive Azure Arc diagnostic tools for troubleshooting and support, and post-deployment Defender for Servers pricing configuration at the resource level. Streamlines the deployment of advanced threat detection, behavioral analytics, just-in-time VM access, adaptive application controls, and integration with Azure Security Center.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Az.Accounts'; ModuleVersion = '2.12.1'; }, 
               @{ModuleName = 'Az.Resources'; ModuleVersion = '6.0.0'; })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'New-AzureArcDevice', 'Get-AzureArcPrerequisite', 
               'Start-ServerProtection', 'Get-AzureArcDiagnostic', 
               'Set-AzureArcResourcePricing'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Azure', 'AzureArc', 'Defender', 'MicrosoftDefender', 'DefenderForServers', 'DFS', 'Security', 'Management', 'Deployment', 'Prerequisites', 'ThreatProtection', 'Enterprise', 'PowerShell', 'Automation', 'Diagnostics', 'Troubleshooting', 'Logging', 'Pricing', 'Configuration', 'PostDeployment', 'ServerProtection', 'VulnerabilityAssessment', 'BehavioralAnalytics', 'SecurityCenter')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/coullessi/PowerShell/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/coullessi/PowerShell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## Version 1.0.0 - Initial Release

### 🛡️ Enterprise-Grade Azure Arc & Defender for Servers (ARC-DFS) Module
Complete PowerShell solution for server protection through Azure Arc onboarding and Microsoft Defender for Servers integration. Streamlines deployment of advanced threat protection, vulnerability assessment, and security monitoring for server workloads in Microsoft Defender for Cloud.

### 🚀 Core Features
- **Comprehensive Prerequisites Testing** - Complete system validation including TLS requirements, network connectivity, and Azure authentication
- **Automated Azure Arc Deployment** - Device creation with Group Policy deployment for enterprise environments
- **Defender for Servers Integration** - Seamless integration with Microsoft Defender for Cloud advanced threat protection
- **Advanced Diagnostics** - Professional troubleshooting and log collection capabilities
- **Pricing Management** - Post-deployment Defender for Servers pricing configuration at resource level
- **Unified File Management** - Standardized directory system ensures all generated files are organized in user-chosen locations
- **Interactive ARC-DFS Interface** - User-friendly menu system with built-in help and guidance
- **Seamless Authentication** - Automated Azure authentication and subscription management

### 🔧 Defender for Servers Capabilities
- Advanced threat detection and behavioral analytics
- Vulnerability assessment and management integration
- Just-in-time VM access and adaptive application controls
- Security recommendations and compliance monitoring
- Multi-device batch processing for enterprise environments
- Comprehensive Azure Arc diagnostic tools for troubleshooting and support
- Enterprise-scale automated agent installation with security monitoring
- Resource-level pricing configuration for cost optimization

### 🎯 Simplified User Experience
- Single ARC-DFS ASCII art presentation in Start-ServerProtection for clean interface
- Streamlined workflow focused on essential server protection functions
- Removed non-essential files for simplified deployment

For complete documentation and support: https://github.com/coullessi/PowerShell
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/coullessi/PowerShell/tree/main/PSModules/ServerProtection'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
